# Generated by Django 6.0.3 on 2026-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
