# Generated by Django 6.0.5 on 2026-06-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_roll_number_profile_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='staff_id',
        ),
    ]
